### ISSUE TITLE
Disable certain linter warnings

### ISSUE THREAD

**Issue by Demnogonis** [jasjuang/SublimeLinter-contrib-lesshint#1]
According to the lesshint documentation you can disable certain linter warnings if you don't care about them by using a .lesshintrc file. How can I apply these settings in the lesshint section of my SublimeLinter.sublime-settings file? I tried the following but with no luck

    "lesshint": {
        "@disable": true,
        "args": [],
        "excludes": [],
        "propertyOrdering": {
            "enabled": false
        },
        "zeroUnit": {
            "style": "no_unit"
        }
        "ignore_match": [
            "propertyOrdering",
            "zeroUnit"
        ]
    },

Am I missing something here?

**Comment by jasjuang** [comment]
From my understanding lesshint does not provide a way to disable particular linter warnings on the command line like cpplint, therefore it's not possible to do it in the SublimeLinter.sublime-settings file.

You can either put your .lesshintrc file in the project root and it will be automatically applied.

or

Put your .lesshintrc file in a random place and do something like

``````
"lesshint": {
        "@disable": false,
        "args": [
              	"-c", "/path/to/your/.lesshintrc"
        ],
        "excludes": []
 },
``````

**Comment by Demnogonis** [comment]
Having the file in my project root was not an option but the second approach worked like a charm.

Thank you! 👍
