### ISSUE TITLE
lesshint disabled. 'selector' is mandatory in 'cls.defaults'.

### ISSUE THREAD

**Issue by seanthepottingshed** [jasjuang/SublimeLinter-contrib-lesshint#10]
**Sublime Text** `v3.2.2`, build `3211`
**Sublime Linter** `v4.17.0`

I'm no Python expert but surely this can't be right the`defaults` object here:

* https://github.com/jasjuang/SublimeLinter-contrib-lesshint/blob/master/linter.py#L34-L36

..is being overwritten here:

* https://github.com/jasjuang/SublimeLinter-contrib-lesshint/blob/master/linter.py#L38

**Comment by jasjuang** [comment]
closed via #11
