### ISSUE TITLE
Warnings showing as errors

### ISSUE THREAD

**Issue by dwhiting10** [jasjuang/SublimeLinter-contrib-lesshint#2]
I have been using your plugin in Sublime 3 to validate LESS code.  The plugin seems to work well but for some reason it seems to show what I would think should be warnings as errors.  For example I have about a dozen errors showing in one file that when I investigate the issue the issue it ways the the error is "Property ordering is not alphabetized"  Now, as a best practice, alphabetizing my properties is probably a great idea but not having them alphabetized should only be a warning not an error...

**Comment by jasjuang** [comment]
For linters it's either a warning or not a warning,  if you want to disable the warning "Property ordering is not alphabetized" you can add your own .lesshintrc file to achieve it. You can see #1 for more details.

**Comment by dwhiting10** [comment]
Ok I will take a look at that.  The reason I asked is that I have seen other Sublime linter plugins that seem to be able to distinguish between the two so that the warnings are yellow and the errors are red but maybe lesshint doesn't have that distinction?

**Comment by jasjuang** [comment]
I have used a fair amount of linters myself (cpplint, cmakelint, glsllint, mlint etc...) but I never see something like warnings are yellow and the errors are red, which linter you used have this? I am pretty sure lesshint does not support this kind of functionality though

**Comment by dwhiting10** [comment]
I have seen it in a couple but one of the ones that I use the most that does this is SublimeLinter-jshint [SublimeLinter-jshint](https://github.com/SublimeLinter/SublimeLinter-jshint).  As you can see in the attached screenshot there are two issues with the JavaScript code.  The first one (marked in yellow) is just a warning that I should really use '===' instead of '==' when comparing with null.  The second issue (marked in red) is an error telling me that I forgot add an identifier to that line of code.

![jshint-linter](https://cloud.githubusercontent.com/assets/11296998/24561111/991173a2-1613-11e7-9da7-587878e06b9a.png)

As you say lesshint may not have the ability to do this...

**Comment by jasjuang** [comment]
I tried  jshint myself and if you do something like `jshint --verbose test.js` it actually shows the code W or E in it's output hence sublime is able to parse it differently. For lesshint, at most you can set is the CLI exit codes as shown in [here](https://github.com/lesshint/lesshint/blob/master/lib/linters/README.md), there is no related information in the output about warning or error.
