### ISSUE TITLE
Warnings showing as Errors

### ISSUE THREAD

**Issue by Elaniobro** [jasjuang/SublimeLinter-contrib-lesshint#3]
Hi, I saw the previously closed issue #2. 

Not sure if that response/issue is/was up to date. sublimelinter-contrib-eslint shows yellow for `warning` and red for `error`.

This [issue #44](https://github.com/lesshint/lesshint/issues/44) also indicates that the warning flag is now a part of lesshint.

**Comment by jasjuang** [comment]
@Elaniobro  Interesting, I never tried to overwrite any "warnings" into "errors" so I always treat the "warnings" as errors. 

Since everything is "warnings" by default and it's not immediately obvious to me on how to overwrite "warnings" into "errors", can you let me know to reproduce it?

**Comment by Elaniobro** [comment]
In your .lesshintrc file you can add a `"severity" : "warning"` key/value pair. like so:


```
    "idSelector": {
        "enabled": false,
        "severity": "warning"
    },
    "universalSelector": {
        "enabled": true,
        "severity": "error"
    }
```
If you look in the console of sublime you will see the following:
```
SublimeLinter: lesshint: index.less ['/Users/trybuch/Sites/example/basesite/node_modules/.bin/lesshint', '@'] 
SublimeLinter: lesshint output:
Error: index.less: line 9, col 1, universalSelector: The universal selector shouldn't be used.
Warning: index.less: line 37, col 1, idSelector: Selectors should not use IDs.
```
While this "works" the visual cue is still `Red` and not `Yellow` for both warnings and errors.

**Comment by Elaniobro** [comment]
I think we can close this now. The https://github.com/jasjuang/SublimeLinter-contrib-lesshint/pull/4 fixes this issue!
