### ISSUE TITLE
How do i verify it installed correctly?

### ISSUE THREAD

**Issue by BarbzYHOOL** [jasjuang/SublimeLinter-contrib-lesshint#5]
1) How can I test?

2) Is it better/more up to date than https://github.com/MarkGriffiths/SublimeLinter-contrib-lessc ?

3) Also in the readme it says

> It will be used with files that have the “syntax” syntax.

weird

**Comment by jasjuang** [comment]
1. If everything installed correctly you should be starting to see highlights on the errors, for example create a random file

index.less
```
body { height: 100%; width: 100%; }
```

you will see highlights on "h" and "w"

2. I never used it so can't provide an answer.

3. I just pushed a change to update the README. Thanks for catching the typo.

**Comment by BarbzYHOOL** [comment]
in fact i had configured sublimelinter to "on save/onload" that's why I didn't see the highlights :P
