### ISSUE TITLE
Please update readme

### ISSUE THREAD

**Issue by janthemanson** [jasjuang/SublimeLinter-contrib-lesshint#8]
Readme file is referring only to sublimelinter main version 3, but should now compatible up to version 4.16. after implementing the fix.

I think the following mention is also obsolete now:
```
please follow the instructions here.
```
There are no helpful information on the linked documentation page.

Best regards, Jan

**Comment by jasjuang** [comment]
PRs are always welcome!

**Comment by jasjuang** [comment]
closed via #9
